// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfGBIKDbZCPudE15Sb7GuO5JlBtk2ZHms',
    appId: '1:102377783501:android:c57d08b5160cce38002984',
    messagingSenderId: '102377783501',
    projectId: 'project2023-a3ac5',
    databaseURL: 'https://project2023-a3ac5-default-rtdb.firebaseio.com',
    storageBucket: 'project2023-a3ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV9ncGg_maXLF9L0U2-XQ7rQ_gV-6A9ug',
    appId: '1:102377783501:ios:fce9fce720e4e4f4002984',
    messagingSenderId: '102377783501',
    projectId: 'project2023-a3ac5',
    databaseURL: 'https://project2023-a3ac5-default-rtdb.firebaseio.com',
    storageBucket: 'project2023-a3ac5.appspot.com',
    iosBundleId: 'com.example.project2023',
  );
}
